update unicorn

diff --git a/unicorn b/unicorn
--- a/unicorn
+++ b/unicorn
@@ -4,9 +4,17 @@ APP_NAME=redmine
 RAILS_ENV=production
 
 APP_ROOT="/home/git/redmine"
-
+APP_USER="git"
 PID="${APP_ROOT}/tmp/pids/unicorn.pid"
 CONF="${APP_ROOT}/config/unicorn.rb"
+
+if ["$USER" != "$APP_USER"]; then
+    sudo -u "$APP_USER" -H -i $0 "$@"; exit;
+fi
+
+if ! cd "$APP_ROOT"; then
+    echo "Faild to cd into $APP_ROOT, exiting!"; exit 1
+fi
 
 start()
 {
